# Generated by Django 6.1.1 on 2026-10-01 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importitem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИИН должен содержать 12 цифр.')], verbose_name='ИИН')),
            ],
            options={
                'verbose_name': 'должник',
                'verbose_name_plural': 'должники',
                'db_table': 'debtors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='ДБЗ')),
                ('purchase_principal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Основной долг (выкуп)')),
                ('purchase_interest', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Вознаграждение (выкуп)')),
                ('purchase_penalties', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Пеня/Штрафы (выкуп)')),
                ('purchase_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Дебиторская задолженность (выкуп)')),
                ('purchase_state_duty', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Гос.пошлина (выкуп)')),
                ('purchase_representative_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Представительские расходы (выкуп)')),
                ('purchase_notary_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Нотариальные расходы (выкуп)')),
                ('purchase_postal_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Почтовые расходы (выкуп)')),
                ('purchase_total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая сумма задолженности (выкуп)')),
                ('pkb_state_duty_total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Гос.пошлина (ПКБ), начислено')),
                ('pkb_representative_expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Представительские расходы (ПКБ), начислено')),
                ('pkb_notary_expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Нотариальные расходы (ПКБ), начислено')),
                ('pkb_postal_expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Почтовые расходы (ПКБ), начислено')),
                ('pkb_claim_security_total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Обеспечение иска (ПКБ), начислено')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая сумма задолженности')),
                ('payments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма платежей')),
                ('principal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Основной долг')),
                ('interest_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Вознаграждение')),
                ('penalties_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Пеня/Штрафы')),
                ('purchase_receivable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Дебиторская задолженность (остаток по выкупу)')),
                ('pkb_state_duty_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Гос.пошлина (ПКБ), остаток')),
                ('pkb_representative_expenses_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Представительские расходы (ПКБ), остаток')),
                ('pkb_notary_expenses_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Нотариальные расходы (ПКБ), остаток')),
                ('pkb_postal_expenses_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Почтовые расходы (ПКБ), остаток')),
                ('pkb_claim_security_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Обеспечение иска (ПКБ), остаток')),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Списание')),
                ('write_off_date', models.DateField(blank=True, null=True, verbose_name='Дата списания')),
                ('court_adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Изменения по решению суда, приказы')),
                ('court_cancellation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РС, МС, отмена')),
                ('overpayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Переплата')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Актуальный остаток')),
                ('check_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Проверка')),
                ('final_debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Итоговый остаток задолженности')),
                ('repayment_date', models.DateField(blank=True, null=True, verbose_name='Дата погашения')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='imports.debtor', verbose_name='Должник')),
            ],
            options={
                'verbose_name': 'задолженность',
                'verbose_name_plural': 'задолженности',
                'db_table': 'debts',
                'ordering': ['contract_number'],
            },
        ),
    ]
