# Generated by Django 6.1.1 on 2026-10-02 04:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def initialize_contract_totals(apps, schema_editor):
    Debt = apps.get_model('imports', 'Debt')

    for debt in Debt.objects.prefetch_related('payments'):
        payments = sorted(debt.payments.all(), key=lambda item: (item.payment_date, item.pk))
        paid_amount = sum((payment.amount for payment in payments), Decimal('0'))
        total_debt = debt.purchase_total_debt
        outstanding_amount = max(total_debt - paid_amount, Decimal('0'))
        overpayment_amount = max(paid_amount - total_debt, Decimal('0'))
        closed_at = None
        status = 'active'
        if total_debt > 0 and paid_amount >= total_debt:
            running_total = Decimal('0')
            for payment in payments:
                running_total += payment.amount
                if running_total >= total_debt:
                    closed_at = payment.payment_date
                    break
            status = 'closed'
        Debt.objects.filter(pk=debt.pk).update(
            paid_amount=paid_amount,
            outstanding_amount=outstanding_amount,
            overpayment_amount=overpayment_amount,
            status=status,
            closed_at=closed_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0014_add_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='debt',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='debt',
            name='overpayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Переплата'),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=20, verbose_name='Статус договора'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('active', 'Без возврата'), ('partially_refunded', 'Частично возвращён'), ('refunded', 'Возвращён полностью')], default='active', max_length=30, verbose_name='Статус возврата'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Возвращено'),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма возврата')),
                ('refund_date', models.DateField(verbose_name='Дата возврата')),
                ('reason', models.TextField(verbose_name='Основание')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='imports.payment', verbose_name='Исходный платёж')),
            ],
            options={
                'verbose_name': 'возврат платежа',
                'verbose_name_plural': 'возвраты платежей',
                'db_table': 'payment_refunds',
                'ordering': ['-refund_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_refund_amount_positive')],
            },
        ),
        migrations.RunPython(
            initialize_contract_totals,
            migrations.RunPython.noop,
        ),
    ]
