# Generated by Django 6.1.1 on 2026-10-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0017_financial_change_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='written_off_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Списано'),
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeoff_date', models.DateField(verbose_name='Дата списания')),
                ('kind', models.CharField(choices=[('full', 'Полное списание'), ('partial', 'Частичное списание')], max_length=20, verbose_name='Тип списания')),
                ('category', models.CharField(blank=True, choices=[('purchase_interest', 'Вознаграждение (выкуп)'), ('purchase_penalties', 'Пеня/Штрафы (выкуп)'), ('purchase_receivable', 'Дебиторская задолженность (выкуп)'), ('purchase_state_duty', 'Гос.пошлина (выкуп)'), ('purchase_representative_expenses', 'Представительские расходы (выкуп)'), ('purchase_notary_expenses', 'Нотариальные расходы (выкуп)'), ('purchase_postal_expenses', 'Почтовые расходы (выкуп)')], max_length=40, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма списания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('debt', models.ForeignKey(db_column='debt_id', on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='imports.debt', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'списание',
                'verbose_name_plural': 'списания',
                'db_table': 'writeoffs',
                'ordering': ['-writeoff_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='writeoff_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('category', ''), ('kind', 'full')), models.Q(('category__in', ('purchase_interest', 'purchase_penalties', 'purchase_receivable', 'purchase_state_duty', 'purchase_representative_expenses', 'purchase_notary_expenses', 'purchase_postal_expenses')), ('kind', 'partial')), _connector='OR'), name='writeoff_kind_category_valid')],
            },
        ),
    ]
