# Generated by Django 6.1.1 on 2026-10-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0018_debt_written_off_amount_writeoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialchangerequest',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('approve_financialchangerequest', 'Может подтверждать изменения платежей и расходов')], 'verbose_name': 'заявка на изменение финансовой записи', 'verbose_name_plural': 'заявки на изменение финансовых записей'},
        ),
        migrations.AlterField(
            model_name='financialchangerequest',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='imports.expense', verbose_name='Расход'),
        ),
    ]
