# Generated by Django 6.1.1 on 2026-10-02 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0019_alter_financialchangerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение'), ('snapshot', 'Значения на момент включения истории')], max_length=20, verbose_name='Событие')),
                ('old_data', models.JSONField(default=dict, verbose_name='Было')),
                ('new_data', models.JSONField(verbose_name='Стало')),
                ('reason', models.TextField(blank=True, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_value_history', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_history', to='imports.expense')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_history', to='imports.payment')),
                ('writeoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_history', to='imports.writeoff')),
            ],
            options={
                'verbose_name': 'история значений финансовой записи',
                'verbose_name_plural': 'история значений финансовых записей',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('expense__isnull', True), ('payment__isnull', False), ('writeoff__isnull', True)), models.Q(('expense__isnull', False), ('payment__isnull', True), ('writeoff__isnull', True)), models.Q(('expense__isnull', True), ('payment__isnull', True), ('writeoff__isnull', False)), _connector='OR'), name='financial_history_has_one_record')],
            },
        ),
    ]
