# Generated by Django 6.1.1 on 2026-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0021_existing_financial_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('review', 'Ожидает подтверждения'), ('cancelled', 'Отменён'), ('processing', 'Обрабатывается'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='new', max_length=20),
        ),
    ]
