# Generated by Django 6.1.1 on 2026-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0023_writeoff_import_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoff',
            name='distribution',
            field=models.JSONField(blank=True, default=dict, verbose_name='Распределение по категориям'),
        ),
    ]
