# Generated by Django 6.1.1 on 2026-10-02 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0024_writeoff_distribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='writeoff',
            name='writeoff_kind_category_valid',
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='category',
            field=models.CharField(blank=True, choices=[('purchase_principal', 'Основной долг'), ('purchase_interest', 'Вознаграждение (выкуп)'), ('purchase_penalties', 'Пеня/Штрафы (выкуп)'), ('purchase_receivable', 'Дебиторская задолженность (выкуп)'), ('purchase_state_duty', 'Гос.пошлина (выкуп)'), ('purchase_representative_expenses', 'Представительские расходы (выкуп)'), ('purchase_notary_expenses', 'Нотариальные расходы (выкуп)'), ('purchase_postal_expenses', 'Почтовые расходы (выкуп)'), ('state_duty', 'Гос. пошлина наша'), ('representative_expenses', 'Представительские расходы наши'), ('notary_expenses', 'Нотариальные расходы наши'), ('postal_expenses', 'Почтовые расходы наши'), ('claim_security', 'Обеспечение иска'), ('additional_expenses', 'Дополнительные расходы')], max_length=40, verbose_name='Категория'),
        ),
        migrations.AddConstraint(
            model_name='writeoff',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', ''), ('kind', 'full')), models.Q(('category__in', ('purchase_principal', 'purchase_interest', 'purchase_penalties', 'purchase_receivable', 'purchase_state_duty', 'purchase_representative_expenses', 'purchase_notary_expenses', 'purchase_postal_expenses', 'state_duty', 'representative_expenses', 'notary_expenses', 'postal_expenses', 'claim_security', 'additional_expenses')), ('kind', 'partial')), _connector='OR'), name='writeoff_kind_category_valid'),
        ),
    ]
