# Generated by Django 6.1.1 on 2026-10-02 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0026_freeze_writeoff_distributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('bin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{12}$', 'БИН должен содержать 12 цифр.')], verbose_name='БИН')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'коллекторское агентство',
                'verbose_name_plural': 'коллекторские агентства',
                'db_table': 'collection_agencies',
                'ordering': ['name', 'pk'],
            },
        ),
    ]
