# Generated by Django 6.1.1 on 2026-10-02 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0027_collectionagency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, max_length=80, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Основание')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Было / стало / результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='На дату')),
                ('balances', models.JSONField(default=dict)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('overpayment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(max_length=20)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('written_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('calculation_source', models.CharField(default='recalculation', max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('snapshot_date',),
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(choices=[('court', 'Решение суда'), ('enforcement', 'Исполнительный документ'), ('payment', 'Подтверждение платежа'), ('writeoff', 'Документ списания'), ('refund', 'Документ возврата'), ('registry', 'Реестр'), ('other', 'Другой')], max_length=30, verbose_name='Вид')),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
            ],
            options={
                'verbose_name_plural': 'Договоры цессии',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер счёта')),
            ],
            options={
                'verbose_name_plural': 'Счета компаний',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('bin', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'БИН должен содержать 12 цифр.')], verbose_name='БИН')),
            ],
            options={
                'verbose_name_plural': 'Первичные кредиторы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounts', models.JSONField(default=dict)),
                ('overpayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mode', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('region', 'Регионы'), ('kato', 'КАТО'), ('gender', 'Пол'), ('document_type', 'Тип документа'), ('document_issuer', 'Орган выдачи'), ('writeoff_reason', 'Основания списания'), ('cancellation_reason', 'Основания отмены/удаления')], max_length=50, verbose_name='Справочник')),
                ('name', models.CharField(max_length=255, verbose_name='Значение')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
            ],
            options={
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['contract_number'], 'permissions': [('recalculate_debt', 'Запуск полного перерасчёта'), ('export_debt', 'Выгрузка данных и отчётов')], 'verbose_name': 'задолженность', 'verbose_name_plural': 'задолженности'},
        ),
        migrations.RemoveConstraint(
            model_name='writeoff',
            name='writeoff_kind_category_valid',
        ),
        migrations.AddField(
            model_name='debt',
            name='collection_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imports.collectionagency', verbose_name='Коллекторское агентство'),
        ),
        migrations.AddField(
            model_name='debt',
            name='dbz_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание ДБЗ'),
        ),
        migrations.AddField(
            model_name='debt',
            name='dbz_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало ДБЗ'),
        ),
        migrations.AddField(
            model_name='debt',
            name='has_overpayment',
            field=models.BooleanField(default=False, verbose_name='Есть переплата'),
        ),
        migrations.AddField(
            model_name='debt',
            name='issued_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Выданный кредит'),
        ),
        migrations.AddField(
            model_name='debt',
            name='manual_closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ручная дата закрытия'),
        ),
        migrations.AddField(
            model_name='debt',
            name='needs_manual_review',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка'),
        ),
        migrations.AddField(
            model_name='debt',
            name='overdue_days_at_registry_date',
            field=models.PositiveIntegerField(default=0, verbose_name='Дни просрочки на дату реестра'),
        ),
        migrations.AddField(
            model_name='debt',
            name='recalculation_error_message',
            field=models.TextField(blank=True, verbose_name='Ошибка перерасчёта'),
        ),
        migrations.AddField(
            model_name='debt',
            name='registry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата реестра'),
        ),
        migrations.AddField(
            model_name='debt',
            name='registry_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер реестра'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи документа'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='document_issuer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Орган выдачи'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='gender',
            field=models.CharField(blank=True, max_length=40, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='kato',
            field=models.CharField(blank=True, max_length=20, verbose_name='КАТО'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='region',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='residential_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='expense',
            name='operation_status',
            field=models.CharField(choices=[('active', 'Действует'), ('corrected', 'Скорректирован'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='distribution',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ручное распределение'),
        ),
        migrations.AddField(
            model_name='payment',
            name='distribution_mode',
            field=models.CharField(choices=[('automatic', 'Автоматическое'), ('manual', 'Ручное')], default='automatic', max_length=20, verbose_name='Распределение'),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_comment',
            field=models.TextField(blank=True, verbose_name='Причина ручного распределения'),
        ),
        migrations.AddField(
            model_name='payment',
            name='operation_status',
            field=models.CharField(choices=[('active', 'Действует'), ('corrected', 'Скорректирован'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата перевода'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='operation_status',
            field=models.CharField(choices=[('active', 'Действует'), ('corrected', 'Скорректирован'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Основание списания'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт'), ('closed_paid', 'Закрыт платежами'), ('closed_written_off', 'Закрыт списанием'), ('closed_mixed', 'Закрыт платежами и списаниями'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус договора'),
        ),
        migrations.AddConstraint(
            model_name='writeoff',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', ''), ('kind', 'full')), models.Q(('category', ''), ('kind', 'partial')), models.Q(('category__in', ('purchase_principal', 'purchase_interest', 'purchase_penalties', 'purchase_receivable', 'purchase_state_duty', 'purchase_representative_expenses', 'purchase_notary_expenses', 'purchase_postal_expenses', 'state_duty', 'representative_expenses', 'notary_expenses', 'postal_expenses', 'claim_security', 'additional_expenses')), ('kind', 'partial')), _connector='OR'), name='writeoff_kind_category_valid'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancesnapshot',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='imports.debt'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='imports.debt'),
        ),
        migrations.AddField(
            model_name='debt',
            name='cession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imports.cession', verbose_name='Договор цессии'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.collectionagency', verbose_name='КА'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imports.companyaccount', verbose_name='Счёт компании'),
        ),
        migrations.AddField(
            model_name='cession',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.creditor', verbose_name='Первичный кредитор'),
        ),
        migrations.AddField(
            model_name='debt',
            name='original_creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imports.creditor', verbose_name='Первичный кредитор'),
        ),
        migrations.AddField(
            model_name='paymentdistribution',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_distribution', to='imports.payment'),
        ),
        migrations.AddConstraint(
            model_name='referencevalue',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='unique_reference_value'),
        ),
        migrations.AddConstraint(
            model_name='balancesnapshot',
            constraint=models.UniqueConstraint(fields=('debt', 'snapshot_date'), name='unique_balance_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='cession',
            constraint=models.UniqueConstraint(fields=('number', 'date', 'creditor'), name='unique_cession'),
        ),
    ]
