# Generated by Django 6.1.1 on 2026-10-05 05:20

from django.db import migrations


def remove_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label='imports', content_type__model='debt',
        codename__in=('change_debt', 'delete_debt'),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('imports', '0029_project_reference_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'default_permissions': ('add', 'view'), 'ordering': ['contract_number'], 'permissions': [('recalculate_debt', 'Запуск полного перерасчёта'), ('export_debt', 'Выгрузка данных и отчётов')], 'verbose_name': 'задолженность', 'verbose_name_plural': 'задолженности'},
        ),
        migrations.RunPython(remove_permissions, migrations.RunPython.noop),
    ]
