# Generated by Django 6.1.1 on 2026-10-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0030_remove_contract_mutation_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='import_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='imports.importitem', verbose_name='Исходная строка импорта'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='import_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='imports.importitem', verbose_name='Исходная строка импорта'),
        ),
        migrations.AddField(
            model_name='expense',
            name='import_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='imports.importitem', verbose_name='Исходная строка импорта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='import_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='imports.importitem', verbose_name='Исходная строка импорта'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='import_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='imports.importitem', verbose_name='Исходная строка импорта'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='import_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='imports.importitem', verbose_name='Исходная строка импорта'),
        ),
    ]
