# Generated by Django 6.1.1 on 2026-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0032_restore_import_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='check_file',
            field=models.FileField(blank=True, editable=False, upload_to='import_checks/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='import',
            name='check_heartbeat',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
