# Generated by Django 6.1.1 on 2026-10-05 07:12

from django.db import migrations


def remove_document_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.using(schema_editor.connection.alias).filter(
        app_label='imports', model='casedocument',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0033_background_import_checks'),
        ('users', '0003_project_roles'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDocument',
        ),
        migrations.RunPython(remove_document_permissions, migrations.RunPython.noop),
    ]
