# Generated by Django 6.1.1 on 2026-10-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0044_group_refund_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportApplicationProgress',
            fields=[
                ('import_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='application_progress', serialize=False, to='imports.import')),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('token', models.CharField(blank=True, max_length=32)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('review', 'Ожидает подтверждения'), ('cancelled', 'Отменён'), ('processing', 'Обрабатывается'), ('importing', 'Импорт'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='new', max_length=20),
        ),
    ]
