# Generated by Django 6.1.1 on 2026-10-08 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0045_import_application_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('include_errors', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Ожидает подготовки'), ('processing', 'Подготовка файла'), ('completed', 'Файл готов'), ('failed', 'Ошибка подготовки')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(default='Ожидание', max_length=40)),
                ('token', models.CharField(blank=True, max_length=32)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='import_exports/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='imports.import')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'processing'])), fields=('import_record', 'requested_by', 'include_errors'), name='unique_active_import_export')],
            },
        ),
    ]
