# Generated by Django 6.1.1 on 2026-10-08 03:33

import imports.report_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0046_background_import_exports'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexportjob',
            name='cached_file',
            field=models.FileField(blank=True, storage=imports.report_storage.ImportReportStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='importexportjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает подготовки'), ('processing', 'Подготовка файла'), ('completed', 'Файл готов'), ('failed', 'Ошибка подготовки'), ('expired', 'Файл недоступен')], default='queued', max_length=16),
        ),
    ]
